### PR TITLE
Mint Clone for Review

### PR DESCRIPTION
**Pull request by keddo**
**Building HTML Form of Mint** 
- Added the top signup button and forget password text and styled
- Sing up form added
- Footer section added
- Style added to all the above components

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @keddo, you have done a great job 👍 Before we move ahead let us make some changes. Find comments below:
- Let us create a stickler file and enable stickler for the repo by visiting stickler-ci.com
- Let us change this ```<input type="text" name="phone" id="phone">```  to ```<input type="tel" name="phone" id="phone">```
- Let us fix the errors and warnings returned by the w3validator
sav1
- Let us reposition the form and the signin button to the appropriate position
Currently
sav

Great job ✋ 

Kindly make these changes and submit another code review 😄 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Comment by keddo** [comment]
###  **Changes Made to TSE Review**
- Stickler enabled for the repo
- Input type text changed to tel for the phone number
- Fixed HTML5 validation errors and warning
- Singin button and form got positioned appropriately.

**Comment by Dandush03** [comment]
# :red_circle: Status: Required Changes :red_circle:
### Hey :wave: 
## You're almost there :muscle: :+1: 

## Your project looks great! but is a very important thing you have to consider before submitting another code review :point_down: 

- [ ] Check HTML markup with this [validator](https://validator.w3.org/) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
 > it's throwing the following error
Screenshot from 2020-04-11 22-32-28

## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by keddo** [comment]
### Duplicate attribute alt got removed

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED** :100: :1st_place_medal: :100: 

Hi @keddo :smile: :smile: 

Congrats for this project, it looks professional and it was approved :fireworks: :fireworks: :fireworks: 

:v: Can you please update your live version, on the readme, before you merge it into master? :smile_cat: 

_SUGGESTION FOR THE NEXT PROJECTS:_

:v: You can create a feature branch with a more descriptive name on the next projects, like ''main-page'' or ''mint-page'' instead of ''feature-branch', for example. It will be more descriptive.



If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next project** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

:v: Are you working alone in this project? Why? :thinking:

**Pull request merged**
